version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: ejercicio-3
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: prueba
    ports:
      - "3310:3306"  # Mapeamos el puerto 3310 del host al 3306 del contenedor
    volumes:
      - mysql-data-ejercicio-3:/var/lib/mysql
    networks:
      - mysql-net

volumes:
  mysql-data-ejercicio-3:

networks:
  mysql-net: